### ISSUE TITLE
Front page: Upcoming Meetings

### ISSUE THREAD

**Issue by pfey03** [dictyBase/frontpage-dictybase#107]
Would it be possible to order the meetings on the front page by date such as the the most recent is on top? Also, I replaced one that’s already over. This would make the current display: (the ascb meeting is an important one for Dicty people)

Dicty 2015 Royal Holloway University, London (UK)  [August 9-13, 2015]

The 10th International Conference on Genomics China [Oct 22-25, 2015]

2015 Cell Biology, ASCB annual meeting San Diego (USA( [Dec 12-16, 2015])

Dicty 2016 Arizona (USA) [August 9-13, 2016]

Also, is there a way to not display meetings that were in the past when clicking on ‘more’? If need be I can find more meetings to fill the list that are in the future.

**Comment by biodavidjm** [comment]
Hey Petra, would you mind to send me more upcoming meetings? I just need 

name: "Name of the Meeting"
date: "The date"
location: "City (country)"

Thanks
