### ISSUE TITLE
alternative front page design

### ISSUE THREAD

**Issue by pfey03** [dictyBase/frontpage-dictybase#37]
As sent to Genesis 4/1/15

![fig2](https://cloud.githubusercontent.com/assets/1349602/6969149/8d96e128-d96c-11e4-8d88-563be89000f5.png)

**Comment by biodavidjm** [comment]
Implementing suggestions on branch [feature/petraSuggestions](https://github.com/dictyBase/frontpage-dictybase/tree/feature/petraSuggestions)

**Comment by biodavidjm** [comment]
First step completed: Inserting the **upcoming meetings** in the left main column under the carrousel (758f2fc240dd41a3231d31403a82e694de655645)
