### ISSUE TITLE
Training topics

### ISSUE THREAD

**Issue by biodavidjm** [dictyBase/frontpage-dictybase#38]
Things to study/revise:

##  [Vagrant](https://www.vagrantup.com/)
- [x] Run a bare mininum centos7 vm with at least 30GB hard drive. Use this [box](https://atlas.hashicorp.com/chef/boxes/centos-7.0) to start.
- [x] Setup that box with both port forwarding and [private networking](http://docs.vagrantup.com/v2/networking/private_network.html)
- [x] Install docker and docker-compose in the vm and save the state.

##  [Docker](https://www.docker.com/)
- [x]  **Dockerizing Applications** (Must)
- [x]  **Working with Containers** (Must)
- [x]  **Working with Docker Images** (Must)
- [x] Linking Containers Together (Optional)
- [x] Managing Data in Containers (Optional)

## Deployment on production system
- [x] [Ansible](http://docs.ansible.com/index.html)

**Comment by cybersiddhu** [comment]
https://github.com/dictybase-docker/frontpage/issues/1
