### ISSUE TITLE
Adjust configurations for installation

### ISSUE THREAD

**Issue by biodavidjm** [dictyBase/frontpage-dictybase#44]
- [x] Create a new branch `feature/adjust-config`
- [x] Revise and adjust the configuration files of the project to facilitate the installation and execution anywhere.
   + `package.js`
   + `bower.json`
   + `Gruntfile.js`

**Comment by cybersiddhu** [comment]
I think you only need to adjust `package.json`, have all the dependencies being defined for running the `grunt build` commnd or whatever command you need to generate the distribution. 
Also figure out the `npm` command to run which will install only those dependencies.

**Comment by cybersiddhu** [comment]
* List of dependencies does not need to be duplicated in runtime and dev install sections.
* The dependencies should include bower.

**Comment by cybersiddhu** [comment]
https://github.com/dictybase-docker/frontpage/issues/1
