### ISSUE TITLE
Removing hashtag

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/frontpage-dictybase#98]
The urls should be without any hashtag(#)

**Comment by biodavidjm** [comment]
Exploring documentation.

- [This might be the way to go](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode)

**Comment by cybersiddhu** [comment]
The `html5mode` is true, however not the web server configuration.
You have to modify the response inside the docker container.
